### Data Reading

In [ ]:
df1=spark.read.format("csv").option("header","true").option("inferSchema","true").load("/Volumes/workspace/default/tutorial_learning/raw/customers.csv")

In [ ]:
df1.display()

customer_id,customer_name,city,state,country,signup_date
1,Ritu Ghosh,Howrah,West Bengal,India,2022-06-26
2,Aryan Bose,Bhopal,Madhya Pradesh,India,2022-12-07
3,Deepa Tiwari,Indore,Madhya Pradesh,India,2022-02-26
4,Amit Tiwari,Warangal,Telangana,India,2024-05-04
5,Rajesh Verma,Kolkata,West Bengal,India,2024-05-01
6,Aditya Joshi,Surat,Gujarat,India,2023-03-24
7,Vikram Rao,Warangal,Telangana,India,2022-07-22
8,Simran Menon,Guwahati,Assam,India,2023-11-28
9,Vivaan Roy,Ranchi,Jharkhand,India,2023-09-25
10,Gaurav Pandey,Bhopal,Madhya Pradesh,India,2024-01-08
11,Ananya Iyer,Bhubaneswar,Odisha,India,2022-07-21
12,Vivaan Banerjee,Coimbatore,Tamil Nadu,India,2022-11-26
13,Kiran Kulkarni,Hyderabad,Telangana,India,2022-12-29
14,Shruti Kulkarni,Bhubaneswar,Odisha,India,2024-06-10
15,Amit Choudhury,Jodhpur,Rajasthan,India,2023-03-30
16,Deepak Das,Delhi,Delhi,India,2022-12-22
17,Sunita Nair,Guwahati,Assam,India,2022-08-04
18,Vikram Patil,Ahmedabad,Gujarat,India,2023-07-09
19,Pooja Bhat,Delhi,Delhi,India,2024-06-05
20,Preeti Shah,Bengaluru,Karnataka,India,2022-01-23

In [ ]:
df2=spark.read.format("csv").option("header","true").option("inferSchema","true").load("/Volumes/workspace/default/tutorial_learning/raw/orders.csv")
df2.display()

order_id,customer_id,order_date,payment_method,order_status
1,31,2025-11-30,Credit Card,Completed
2,1893,2024-10-27,UPI,Completed
3,1083,2024-04-20,Net Banking,Returned
4,1916,2024-11-23,UPI,Completed
5,898,2022-09-13,UPI,Completed
6,1377,2025-05-24,UPI,Completed
7,935,2024-02-13,UPI,Completed
8,445,2025-08-19,UPI,Completed
9,1259,2024-01-17,Credit Card,Cancelled
10,1131,2024-08-22,Cash on Delivery,Processing
11,1215,2025-11-30,UPI,Returned
12,530,2024-01-24,Credit Card,Shipped
13,1937,2025-05-30,Debit Card,Completed
14,738,2024-03-30,UPI,Cancelled
15,1703,2025-08-17,UPI,Cancelled
16,1607,2026-01-01,UPI,Processing
17,874,2026-01-01,Cash on Delivery,Processing
18,566,2024-10-06,Cash on Delivery,Shipped
19,1269,2025-05-06,UPI,Completed
20,1886,2025-06-25,UPI,Completed

In [ ]:
df3=spark.read.format("csv").option("header",True).option("inferSchema",True).load("/Volumes/workspace/default/tutorial_learning/raw/order_items.csv")
df3.display()

order_id,product_id,quantity,unit_price
1,35,1,2865.41
2,29,1,4319.50
2,13,3,2131.33
3,18,1,1854.55
4,60,5,579.94
5,33,1,312.93
6,78,1,876.32
6,72,1,1918.28
6,26,1,1210.27
7,92,1,1591.57
7,86,1,443.28
7,14,1,2714.07
8,37,4,1389.36
9,41,1,994.52
9,85,5,279.38
10,40,2,1418.40
10,17,1,2276.26
11,49,5,1254.37
11,43,1,1760.38
12,8,2,2448.97

In [ ]:
df4=spark.read.format("csv").option("header",True).option("inferSchema",True).load("/Volumes/workspace/default/tutorial_learning/raw/products.csv")
df4.display()

product_id,product_name,category,price
1,Smartphone Pro Max,Electronics,28043.24
2,Wireless Noise Cancelling Earbuds,Electronics,3011.06
3,Ultra-Slim 14-inch Laptop,Electronics,64028.30
4,Fitness Smartwatch with SpO2,Electronics,2324.92
5,Portable Bluetooth Speaker 20W,Electronics,3026.39
6,43-inch 4K Ultra HD Smart TV,Electronics,22709.90
7,Ergonomic Optical Gaming Mouse,Electronics,1169.34
8,Mechanical RGB Gaming Keyboard,Electronics,2448.97
9,10-inch Android Tablet,Electronics,11424.27
10,20000mAh Fast Charging Power Bank,Electronics,1936.14
11,Over-Ear Studio Headphones,Electronics,9461.52
12,1TB External Solid State Drive,Electronics,5690.75
13,7-in-1 USB-C Multiport Adapter,Electronics,2131.33
14,1080p Full HD Streaming Webcam,Electronics,2714.07
15,Dual Band Gigabit Wi-Fi 6 Router,Electronics,3494.53
16,Mini Portable LED Projector,Electronics,13450.97
17,Smart Wi-Fi Home Security Camera,Electronics,2276.26
18,Wireless Charging Pad 15W,Electronics,1854.55
19,Smart Wi-Fi Plug 16A with Energy Monitoring,Electronics,1007.13
20,Action Camera 4K Waterproof,Electronics,7731.56

In [ ]:
from pyspark.sql.functions import *
from pyspark.sql.types import *

### Order value rollup

In [ ]:
df_ord_price=df3.groupBy('order_id').agg(round(sum(col('unit_price')*col('quantity')),0).alias("total_price"))
df_ord_price.display()

order_id,total_price
12,6090.0
18,6794.0
38,367.0
67,3641.0
70,5687.0
93,33742.0
161,7537.0
186,558.0
190,471.0
218,27889.0
225,987.0
257,14943.0
261,11382.0
263,973.0
273,29726.0
275,9300.0
280,13943.0
295,1007.0
300,1596.0
317,356.0

In [ ]:
df_ord_price.printSchema()

root
 |-- order_id: integer (nullable = true)
 |-- total_price: double (nullable = true)

###  Validate data types

In [ ]:
df1.printSchema()

root
 |-- customer_id: integer (nullable = true)
 |-- customer_name: string (nullable = true)
 |-- city: string (nullable = true)
 |-- state: string (nullable = true)
 |-- country: string (nullable = true)
 |-- signup_date: date (nullable = true)

In [ ]:
df2.printSchema()

root
 |-- order_id: integer (nullable = true)
 |-- customer_id: integer (nullable = true)
 |-- order_date: date (nullable = true)
 |-- payment_method: string (nullable = true)
 |-- order_status: string (nullable = true)

In [ ]:
df3.printSchema()

root
 |-- order_id: integer (nullable = true)
 |-- product_id: integer (nullable = true)
 |-- quantity: integer (nullable = true)
 |-- unit_price: double (nullable = true)

In [ ]:
df4.printSchema()

root
 |-- product_id: integer (nullable = true)
 |-- product_name: string (nullable = true)
 |-- category: string (nullable = true)
 |-- price: double (nullable = true)

### Check duplicates in all four tables

In [ ]:
df1.createOrReplaceTempView("customers")
df2.createOrReplaceTempView("orders")
df3.createOrReplaceTempView("order_items")
df4.createOrReplaceTempView("products")
df_ord_price.createOrReplaceTempView("order_price")

In [ ]:
print("customers",df1.count())
print("orders",df2.count())
print("order_items",df3.count())
print("products",df4.count())

customers 2015
orders 10000
order_items 21968
products 100

In [ ]:
print("customers",df1.distinct().count())
print("orders",df2.distinct().count())
print("order_items",df3.distinct().count())
print("products",df4.distinct().count())

customers 2000
orders 10000
order_items 21968
products 100

#### 15 duplicate records in customers table

In [ ]:
select customer_id,count(customer_id) from customers group by customer_id  having count(customer_id)>1

customer_id,count(customer_id)
1111,2
1629,2
376,2
1040,2
1261,2
1433,2
460,2
374,2
1163,2
48,2
402,2
76,2
827,2
1418,2
511,2

### Joining all tables to get complete info

In [ ]:
select 
  c.customer_id,
  c.customer_name,
  c.city,
  c.state,
  c.country,
  c.signup_date,
  o.order_id,
  o.order_date,
  o.payment_method,
  o.order_status,
  i.product_id,
  i.quantity,
  i.unit_price,
  p.product_name,
  p.category,
  p.price
from customers as c
left join orders as o on c.customer_id = o.customer_id
left join order_items as i on o.order_id = i.order_id
left join products as p on i.product_id = p.product_id

customer_id,customer_name,city,state,country,signup_date,order_id,order_date,payment_method,order_status,product_id,quantity,unit_price,product_name,category,price
1,Ritu Ghosh,Howrah,West Bengal,India,2022-06-26,8851,2024-05-17,UPI,Completed,50,1,1105.68,Silent Sweep Quartz Wall Clock 12-inch,Home & Kitchen,1105.68
2,Aryan Bose,Bhopal,Madhya Pradesh,India,2022-12-07,4726,2025-08-02,Debit Card,Completed,90,3,492.26,Caffeine Infused Under Eye Cream 20g,Beauty,492.26
3,Deepa Tiwari,Indore,Madhya Pradesh,India,2022-02-26,3764,2022-05-07,Credit Card,Shipped,45,2,1626.32,100% Pure Cotton King Size Bedsheet,Home & Kitchen,1626.32
4,Amit Tiwari,Warangal,Telangana,India,2024-05-04,9209,2025-02-13,Credit Card,Completed,96,1,320.77,Roasted Granulated Instant Coffee 100g,Grocery,320.77
5,Rajesh Verma,Kolkata,West Bengal,India,2024-05-01,6356,2025-04-01,UPI,Cancelled,45,1,1626.32,100% Pure Cotton King Size Bedsheet,Home & Kitchen,1626.32
6,Aditya Joshi,Surat,Gujarat,India,2023-03-24,6502,2025-02-13,UPI,Completed,34,1,709.99,Athletic Training Track Pants,Clothing,709.99
7,Vikram Rao,Warangal,Telangana,India,2022-07-22,8605,2024-09-26,UPI,Completed,99,1,458.92,Creamy Unsweetened Peanut Butter 1kg,Grocery,458.92
8,Simran Menon,Guwahati,Assam,India,2023-11-28,6430,2025-02-07,Credit Card,Completed,36,4,601.90,Soft Merino Woolen Muffler Scarf,Clothing,601.90
9,Vivaan Roy,Ranchi,Jharkhand,India,2023-09-25,9378,2025-07-06,Debit Card,Shipped,48,1,1218.45,Airtight Food Storage Containers (Set of 6),Home & Kitchen,1218.45
10,Gaurav Pandey,Bhopal,Madhya Pradesh,India,2024-01-08,8613,2024-05-18,UPI,Returned,53,2,620.53,Silicone Non-Stick Baking Mat,Home & Kitchen,620.53
11,Ananya Iyer,Bhubaneswar,Odisha,India,2022-07-21,6139,2025-08-01,UPI,Completed,57,1,1180.99,Python for Data Analysis (3rd Edition),Books,1180.99
12,Vivaan Banerjee,Coimbatore,Tamil Nadu,India,2022-11-26,8995,2025-10-14,Credit Card,Completed,27,4,2010.30,Fleece Pullover Winter Hoodie,Clothing,2010.30
13,Kiran Kulkarni,Hyderabad,Telangana,India,2022-12-29,7909,2024-12-12,Credit Card,Processing,65,1,386.47,Ikigai: The Japanese Secret to a Long Life,Books,386.47
14,Shruti Kulkarni,Bhubaneswar,Odisha,India,2024-06-10,4429,2025-09-08,UPI,Completed,40,2,1418.40,Hard Anodized Non-Stick Frying Pan,Home & Kitchen,1418.40
15,Amit Choudhury,Jodhpur,Rajasthan,India,2023-03-30,7700,2024-03-28,UPI,Cancelled,1,1,28043.24,Smartphone Pro Max,Electronics,28043.24
16,Deepak Das,Delhi,Delhi,India,2022-12-22,9061,2024-12-18,UPI,Shipped,68,1,306.66,To Kill a Mockingbird,Books,306.66
17,Sunita Nair,Guwahati,Assam,India,2022-08-04,8631,2024-08-29,UPI,Completed,91,2,432.43,Organic Darjeeling Whole Leaf Green Tea 250g,Grocery,432.43
18,Vikram Patil,Ahmedabad,Gujarat,India,2023-07-09,6897,2024-06-25,Credit Card,Shipped,38,1,1342.05,Women's Embroidered Palazzo Pants,Clothing,1342.05
19,Pooja Bhat,Delhi,Delhi,India,2024-06-05,9931,2025-07-24,Credit Card,Processing,31,5,1451.87,Men's Casual Chino Trousers,Clothing,1451.87
20,Preeti Shah,Bengaluru,Karnataka,India,2022-01-23,9268,2022-04-24,UPI,Shipped,66,2,728.79,Good to Great: Why Some Companies Make the Leap,Books,728.79

### Phase 1: Order and sales analysis

#### Order-level dataset (orders + order value)

In [ ]:
select o.*,op.total_price from orders as o left join order_price as op on o.order_id = op.order_id

order_id,customer_id,order_date,payment_method,order_status,total_price
1,31,2025-11-30,Credit Card,Completed,2865.0
2,1893,2024-10-27,UPI,Completed,10713.0
3,1083,2024-04-20,Net Banking,Returned,1855.0
4,1916,2024-11-23,UPI,Completed,2900.0
5,898,2022-09-13,UPI,Completed,313.0
6,1377,2025-05-24,UPI,Completed,4005.0
7,935,2024-02-13,UPI,Completed,4749.0
8,445,2025-08-19,UPI,Completed,5557.0
9,1259,2024-01-17,Credit Card,Cancelled,2391.0
10,1131,2024-08-22,Cash on Delivery,Processing,5113.0
11,1215,2025-11-30,UPI,Returned,8032.0
12,530,2024-01-24,Credit Card,Shipped,6090.0
13,1937,2025-05-30,Debit Card,Completed,6455.0
14,738,2024-03-30,UPI,Cancelled,16849.0
15,1703,2025-08-17,UPI,Cancelled,954.0
16,1607,2026-01-01,UPI,Processing,27442.0
17,874,2026-01-01,Cash on Delivery,Processing,2377.0
18,566,2024-10-06,Cash on Delivery,Shipped,6794.0
19,1269,2025-05-06,UPI,Completed,39322.0
20,1886,2025-06-25,UPI,Completed,7303.0

In [ ]:
dfo1=dfo.withColumn('month',month('order_date')).withColumn('year',year('order_date'))

In [ ]:
dfo1.display()

order_id,customer_id,order_date,payment_method,order_status,total_price,month,year
1,31,2025-11-30,Credit Card,Completed,2865.0,11,2025
2,1893,2024-10-27,UPI,Completed,10713.0,10,2024
3,1083,2024-04-20,Net Banking,Returned,1855.0,4,2024
4,1916,2024-11-23,UPI,Completed,2900.0,11,2024
5,898,2022-09-13,UPI,Completed,313.0,9,2022
6,1377,2025-05-24,UPI,Completed,4005.0,5,2025
7,935,2024-02-13,UPI,Completed,4749.0,2,2024
8,445,2025-08-19,UPI,Completed,5557.0,8,2025
9,1259,2024-01-17,Credit Card,Cancelled,2391.0,1,2024
10,1131,2024-08-22,Cash on Delivery,Processing,5113.0,8,2024
11,1215,2025-11-30,UPI,Returned,8032.0,11,2025
12,530,2024-01-24,Credit Card,Shipped,6090.0,1,2024
13,1937,2025-05-30,Debit Card,Completed,6455.0,5,2025
14,738,2024-03-30,UPI,Cancelled,16849.0,3,2024
15,1703,2025-08-17,UPI,Cancelled,954.0,8,2025
16,1607,2026-01-01,UPI,Processing,27442.0,1,2026
17,874,2026-01-01,Cash on Delivery,Processing,2377.0,1,2026
18,566,2024-10-06,Cash on Delivery,Shipped,6794.0,10,2024
19,1269,2025-05-06,UPI,Completed,39322.0,5,2025
20,1886,2025-06-25,UPI,Completed,7303.0,6,2025

#### Monthly Revenue

In [ ]:
df_monthly=dfo1.filter(col('order_status').isin(['Shipped','Processing','Completed'])).groupby('year','month').agg(countDistinct('order_id').alias('total_orders'),sum('total_price').alias('total_revenue')).orderBy('year','month')

In [ ]:
df_monthly.display()

year,month,total_orders,total_revenue
2022,1,2,4866.0
2022,2,6,82008.0
2022,3,13,192515.0
2022,4,31,293577.0
2022,5,30,266221.0
2022,6,33,278930.0
2022,7,39,478624.0
2022,8,44,418824.0
2022,9,50,456042.0
2022,10,58,589618.0
2022,11,59,466470.0
2022,12,75,747807.0
2023,1,84,1313268.0
2023,2,74,922990.0
2023,3,90,996687.0
2023,4,108,1093218.0
2023,5,124,975775.0
2023,6,123,984639.0
2023,7,137,1507675.0
2023,8,147,1626940.0
2023,9,139,1039067.0
2023,10,164,1976372.0
2023,11,161,1561343.0
2023,12,213,1915612.0
2024,1,209,2871471.0
2024,2,236,2755052.0
2024,3,237,2311981.0
2024,4,255,3073714.0
2024,5,270,2526601.0
2024,6,251,2004190.0
2024,7,272,2917871.0
2024,8,300,3638453.0
2024,9,287,2663438.0
2024,10,291,2474414.0
2024,11,274,2468219.0
2024,12,280,2790986.0
2025,1,262,2865723.0
2025,2,266,2690764.0
2025,3,292,3684653.0
2025,4,300,3582084.0
2025,5,291,3445722.0
2025,6,246,3042674.0
2025,7,286,4027962.0
2025,8,287,3342643.0
2025,9,283,3103440.0
2025,10,295,2709971.0
2025,11,257,3038270.0
2025,12,298,3492682.0
2026,1,274,2987419.0

#### Yearly Revenue

In [ ]:
df_yearly=dfo1.filter(col('year')<=2025).filter(col('order_status').isin(['Shipped','Processing','Completed'])).groupby('year').agg(sum('total_price').alias('total_revenue'),countDistinct('order_id').alias('total_orders')).orderBy('year')

In [ ]:
df_yearly.withColumn('AOV',round(col('total_revenue')/col('total_orders'),2)).display()

year,total_revenue,total_orders,AOV
2022,4275502.0,440,9717.05
2023,15913586.0,1564,10174.93
2024,32496390.0,3162,10277.16
2025,39026588.0,3363,11604.69

#### Order Status Analysis

In [ ]:
df.groupby('order_status').agg(count('customer_id').alias('count')).display()

order_status,count
Shipped,3448
Returned,1047
None,15
Cancelled,1562
Processing,1555
Completed,14407

#### Payment method analysis

In [ ]:
dfo1.groupby('payment_method').agg(countDistinct('order_id').alias('total_orders'),sum('total_price').alias('total_revenue')).display()

payment_method,total_orders,total_revenue
Credit Card,2129,23894333.0
Debit Card,1452,16808488.0
UPI,4346,45587980.0
Cash on Delivery,1202,10949197.0
None,60,567481.0
Net Banking,811,9248320.0

### Phase 2: Product analysis

In [ ]:
select oi.*,o.order_status,p.product_name,p.category,p.price from order_items as oi left join orders as o on oi.order_id = o.order_id left join products as p on oi.product_id = p.product_id

order_id,product_id,quantity,unit_price,order_status,product_name,category,price
1,35,1,2865.41,Completed,Pure Linen Casual Button-Down Shirt,Clothing,2865.41
2,29,1,4319.50,Completed,Pure Banarasi Art Silk Saree,Clothing,4319.50
2,13,3,2131.33,Completed,7-in-1 USB-C Multiport Adapter,Electronics,2131.33
3,18,1,1854.55,Returned,Wireless Charging Pad 15W,Electronics,1854.55
4,60,5,579.94,Completed,Sapiens: A Brief History of Humankind,Books,579.94
5,33,1,312.93,Completed,Cotton Ankle Length Socks (Pack of 3),Clothing,312.93
6,78,1,876.32,Completed,Anti-Fog UV Protection Swimming Goggles,Sports,876.32
6,72,1,1918.28,Completed,Kashmir Willow Full Size Cricket Bat,Sports,1918.28
6,26,1,1210.27,Completed,Women's Casual Cotton Maxi Dress,Clothing,1210.27
7,92,1,1591.57,Completed,Cold-Pressed Extra Virgin Olive Oil 1L,Grocery,1591.57
7,86,1,443.28,Completed,Onion & Bhringraj Anti-Hairfall Shampoo 300ml,Beauty,443.28
7,14,1,2714.07,Completed,1080p Full HD Streaming Webcam,Electronics,2714.07
8,37,4,1389.36,Completed,Lightweight Waterproof Rain Jacket,Clothing,1389.36
9,41,1,994.52,Cancelled,Ceramic Tea & Coffee Mug Set (Pack of 6),Home & Kitchen,994.52
9,85,5,279.38,Cancelled,Bamboo Charcoal Peel-Off Face Mask,Beauty,279.38
10,40,2,1418.40,Processing,Hard Anodized Non-Stick Frying Pan,Home & Kitchen,1418.40
10,17,1,2276.26,Processing,Smart Wi-Fi Home Security Camera,Electronics,2276.26
11,49,5,1254.37,Returned,Revolving Spice Rack Organizer (16 Jars),Home & Kitchen,1254.37
11,43,1,1760.38,Returned,Cordless Electric Kettle 1.8L,Home & Kitchen,1760.38
12,8,2,2448.97,Shipped,Mechanical RGB Gaming Keyboard,Electronics,2448.97

#### Top 10 products by revenue

In [ ]:
dfo2.filter(col('order_status').isin(['Shipped','Processing','Completed'])).groupby('product_name').agg(sum('quantity').alias('total_quantity'),round(sum(col('quantity')*col('unit_price')),0).alias('total_revenue')).orderBy(col('total_revenue').desc()).limit(10).display()

product_name,total_quantity,total_revenue
Ultra-Slim 14-inch Laptop,320,20489056.0
Smartphone Pro Max,328,9198183.0
43-inch 4K Ultra HD Smart TV,352,7993885.0
Mini Portable LED Projector,377,5071016.0
10-inch Android Tablet,401,4581132.0
Over-Ear Studio Headphones,314,2970917.0
Digital Air Fryer 4.5L,423,2761716.0
Action Camera 4K Waterproof,323,2497294.0
1TB External Solid State Drive,347,1974690.0
Pure Banarasi Art Silk Saree,344,1485908.0

#### Category performance

In [ ]:
from pyspark.sql.window import Window

In [ ]:
dfo2.filter(col('order_status').isin(['Shipped','Processing','Completed'])).groupby('category').agg(sum('quantity').alias('total_quantity'),countDistinct('order_id').alias('total_orders'),round(sum(col('quantity')*col('unit_price')),0).alias('total_revenue')).withColumn('ranking',rank().over(Window.partitionBy().orderBy(col('total_revenue').desc()))).display()

category,total_quantity,total_orders,total_revenue,ranking
Electronics,6719,3262,63647350.0,1
Clothing,5995,2960,9763146.0,2
Home & Kitchen,5497,2730,9338323.0,3
Sports,3858,2028,5025283.0,4
Books,4712,2413,2863605.0,5
Grocery,3367,1742,1847607.0,6
Beauty,3402,1802,1803581.0,7
None,189,104,410505.0,8

### Phase 3: Customer analysis

#### Overview of the joined data

In [ ]:
df.display()

customer_id,customer_name,city,state,country,signup_date,order_id,order_date,payment_method,order_status,product_id,quantity,unit_price,product_name,category,price
1,Ritu Ghosh,Howrah,West Bengal,India,2022-06-26,8851,2024-05-17,UPI,Completed,50,1,1105.68,Silent Sweep Quartz Wall Clock 12-inch,Home & Kitchen,1105.68
2,Aryan Bose,Bhopal,Madhya Pradesh,India,2022-12-07,4726,2025-08-02,Debit Card,Completed,90,3,492.26,Caffeine Infused Under Eye Cream 20g,Beauty,492.26
3,Deepa Tiwari,Indore,Madhya Pradesh,India,2022-02-26,3764,2022-05-07,Credit Card,Shipped,45,2,1626.32,100% Pure Cotton King Size Bedsheet,Home & Kitchen,1626.32
4,Amit Tiwari,Warangal,Telangana,India,2024-05-04,9209,2025-02-13,Credit Card,Completed,96,1,320.77,Roasted Granulated Instant Coffee 100g,Grocery,320.77
5,Rajesh Verma,Kolkata,West Bengal,India,2024-05-01,6356,2025-04-01,UPI,Cancelled,45,1,1626.32,100% Pure Cotton King Size Bedsheet,Home & Kitchen,1626.32
6,Aditya Joshi,Surat,Gujarat,India,2023-03-24,6502,2025-02-13,UPI,Completed,34,1,709.99,Athletic Training Track Pants,Clothing,709.99
7,Vikram Rao,Warangal,Telangana,India,2022-07-22,8605,2024-09-26,UPI,Completed,99,1,458.92,Creamy Unsweetened Peanut Butter 1kg,Grocery,458.92
8,Simran Menon,Guwahati,Assam,India,2023-11-28,6430,2025-02-07,Credit Card,Completed,36,4,601.90,Soft Merino Woolen Muffler Scarf,Clothing,601.90
9,Vivaan Roy,Ranchi,Jharkhand,India,2023-09-25,9378,2025-07-06,Debit Card,Shipped,48,1,1218.45,Airtight Food Storage Containers (Set of 6),Home & Kitchen,1218.45
10,Gaurav Pandey,Bhopal,Madhya Pradesh,India,2024-01-08,8613,2024-05-18,UPI,Returned,53,2,620.53,Silicone Non-Stick Baking Mat,Home & Kitchen,620.53
11,Ananya Iyer,Bhubaneswar,Odisha,India,2022-07-21,6139,2025-08-01,UPI,Completed,57,1,1180.99,Python for Data Analysis (3rd Edition),Books,1180.99
12,Vivaan Banerjee,Coimbatore,Tamil Nadu,India,2022-11-26,8995,2025-10-14,Credit Card,Completed,27,4,2010.30,Fleece Pullover Winter Hoodie,Clothing,2010.30
13,Kiran Kulkarni,Hyderabad,Telangana,India,2022-12-29,7909,2024-12-12,Credit Card,Processing,65,1,386.47,Ikigai: The Japanese Secret to a Long Life,Books,386.47
14,Shruti Kulkarni,Bhubaneswar,Odisha,India,2024-06-10,4429,2025-09-08,UPI,Completed,40,2,1418.40,Hard Anodized Non-Stick Frying Pan,Home & Kitchen,1418.40
15,Amit Choudhury,Jodhpur,Rajasthan,India,2023-03-30,7700,2024-03-28,UPI,Cancelled,1,1,28043.24,Smartphone Pro Max,Electronics,28043.24
16,Deepak Das,Delhi,Delhi,India,2022-12-22,9061,2024-12-18,UPI,Shipped,68,1,306.66,To Kill a Mockingbird,Books,306.66
17,Sunita Nair,Guwahati,Assam,India,2022-08-04,8631,2024-08-29,UPI,Completed,91,2,432.43,Organic Darjeeling Whole Leaf Green Tea 250g,Grocery,432.43
18,Vikram Patil,Ahmedabad,Gujarat,India,2023-07-09,6897,2024-06-25,Credit Card,Shipped,38,1,1342.05,Women's Embroidered Palazzo Pants,Clothing,1342.05
19,Pooja Bhat,Delhi,Delhi,India,2024-06-05,9931,2025-07-24,Credit Card,Processing,31,5,1451.87,Men's Casual Chino Trousers,Clothing,1451.87
20,Preeti Shah,Bengaluru,Karnataka,India,2022-01-23,9268,2022-04-24,UPI,Shipped,66,2,728.79,Good to Great: Why Some Companies Make the Leap,Books,728.79

#### Top customers by spending

In [ ]:
df.filter(col('order_status').isin(['Shipped','Processing','Completed'])).groupby('customer_id','customer_name').agg(countDistinct('order_id').alias('total_orders'),round(sum((col('quantity')*col('unit_price'))),2).alias('total_spent')).orderBy(col('total_spent').desc()).limit(10).display()

customer_id,customer_name,total_orders,total_spent
210,Ananya Roy,4,428998.00
568,Sanjay Dutta,7,424528.38
855,Divya Kumar,7,374729.07
288,Jyoti Pillai,8,372079.79
1144,Swati Yadav,10,367364.30
504,Aryan Bose,7,351973.60
1757,Prisha Patil,4,350832.32
1425,Shruti Choudhury,4,346743.27
148,Ritu Nambiar,5,346112.89
1784,Ritu Iyer,4,345919.10

#### Sales by state or city

In [ ]:
df.filter(col('order_status').isin(['Shipped','Processing','Completed'])).groupby('state').agg(countDistinct('order_id').alias('total_orders'),sum('quantity').alias('total_quantity'),round(sum((col('quantity')*col('unit_price'))),0).alias('total_revenue')).orderBy(col('total_revenue').desc()).display()

state,total_orders,total_quantity,total_revenue
Gujarat,995,3876,11070615.0
Uttar Pradesh,877,3417,9871382.0
Maharashtra,791,3047,8791865.0
Punjab,625,2491,7627816.0
West Bengal,618,2427,7138737.0
Madhya Pradesh,667,2449,6948088.0
Kerala,646,2609,6899619.0
Rajasthan,608,2300,6476100.0
Telangana,555,2147,5304835.0
Karnataka,488,1863,5036336.0
Tamil Nadu,519,2043,4972573.0
Jharkhand,265,1013,3770109.0
Odisha,308,1185,3016571.0
Bihar,280,1094,2944159.0
Assam,271,987,2587833.0
Delhi,247,885,2406405.0

In [ ]:
df.filter(col('order_status').isin(['Shipped','Processing','Completed'])).groupby('city').agg(countDistinct('order_id').alias('total_orders'),sum('quantity').alias('total_quantity'),round(sum((col('quantity')*col('unit_price'))),0).alias('total_revenue')).orderBy(col('total_revenue').desc()).display()

city,total_orders,total_quantity,total_revenue
Ludhiana,372,1481,4522516.0
Indore,387,1418,4224814.0
Noida,303,1224,3996264.0
Vadodara,333,1280,3949813.0
Kolkata,301,1185,3903150.0
Ranchi,263,1008,3766503.0
Kochi,330,1336,3727725.0
Ahmedabad,385,1495,3699889.0
Surat,270,1070,3361049.0
Jaipur,325,1224,3352933.0
Pune,273,1072,3335161.0
Howrah,312,1227,3206482.0
Thiruvananthapuram,316,1273,3171894.0
Chandigarh,250,1003,3099550.0
Jodhpur,279,1068,3098963.0
Nagpur,280,1053,3015692.0
Coimbatore,296,1194,2996298.0
Kanpur,264,1048,2984819.0
Bhubaneswar,302,1163,2961589.0
Patna,276,1079,2923050.0

### Phase 4: Advanced analysis

#### Cancelled orders and potential lost sales

In [ ]:
df.filter(col('order_status').isin(['Cancelled','Completed'])).groupby('order_status').agg(countDistinct('order_id').alias('total_orders'),round(sum((col('quantity')*col('unit_price'))),0).alias('total_revenue')).display()

order_status,total_orders,total_revenue
Cancelled,686,7477568.0
Completed,6520,69957542.0

#### Customer signup cohort

In [ ]:
select c.*,order_id,o.order_date,o.payment_method,o.order_status from customers as c left join orders as o on c.customer_id = o.customer_id

customer_id,customer_name,city,state,country,signup_date,order_id,order_date,payment_method,order_status,signup_month,signupyear
1,Ritu Ghosh,Howrah,West Bengal,India,2022-06-26,8851,2024-05-17,UPI,Completed,6,2022
2,Aryan Bose,Bhopal,Madhya Pradesh,India,2022-12-07,4726,2025-08-02,Debit Card,Completed,12,2022
3,Deepa Tiwari,Indore,Madhya Pradesh,India,2022-02-26,3764,2022-05-07,Credit Card,Shipped,2,2022
4,Amit Tiwari,Warangal,Telangana,India,2024-05-04,9209,2025-02-13,Credit Card,Completed,5,2024
5,Rajesh Verma,Kolkata,West Bengal,India,2024-05-01,6356,2025-04-01,UPI,Cancelled,5,2024
6,Aditya Joshi,Surat,Gujarat,India,2023-03-24,6502,2025-02-13,UPI,Completed,3,2023
7,Vikram Rao,Warangal,Telangana,India,2022-07-22,8605,2024-09-26,UPI,Completed,7,2022
8,Simran Menon,Guwahati,Assam,India,2023-11-28,6430,2025-02-07,Credit Card,Completed,11,2023
9,Vivaan Roy,Ranchi,Jharkhand,India,2023-09-25,9378,2025-07-06,Debit Card,Shipped,9,2023
10,Gaurav Pandey,Bhopal,Madhya Pradesh,India,2024-01-08,8613,2024-05-18,UPI,Returned,1,2024
11,Ananya Iyer,Bhubaneswar,Odisha,India,2022-07-21,6139,2025-08-01,UPI,Completed,7,2022
12,Vivaan Banerjee,Coimbatore,Tamil Nadu,India,2022-11-26,8995,2025-10-14,Credit Card,Completed,11,2022
13,Kiran Kulkarni,Hyderabad,Telangana,India,2022-12-29,7909,2024-12-12,Credit Card,Processing,12,2022
14,Shruti Kulkarni,Bhubaneswar,Odisha,India,2024-06-10,4429,2025-09-08,UPI,Completed,6,2024
15,Amit Choudhury,Jodhpur,Rajasthan,India,2023-03-30,7700,2024-03-28,UPI,Cancelled,3,2023
16,Deepak Das,Delhi,Delhi,India,2022-12-22,9061,2024-12-18,UPI,Shipped,12,2022
17,Sunita Nair,Guwahati,Assam,India,2022-08-04,8631,2024-08-29,UPI,Completed,8,2022
18,Vikram Patil,Ahmedabad,Gujarat,India,2023-07-09,6897,2024-06-25,Credit Card,Shipped,7,2023
19,Pooja Bhat,Delhi,Delhi,India,2024-06-05,9931,2025-07-24,Credit Card,Processing,6,2024
20,Preeti Shah,Bengaluru,Karnataka,India,2022-01-23,9268,2022-04-24,UPI,Shipped,1,2022

In [ ]:
df_info=df_info.withColumn('signup_month',month('signup_date')).withColumn('signupyear',year('signup_date'))

In [ ]:
df_info.groupby('signupyear','signup_month').agg(countDistinct('customer_id').alias('total_customers')).orderBy('signupyear','signup_month').display()

signupyear,signup_month,total_customers
2022,1,65
2022,2,61
2022,3,85
2022,4,54
2022,5,74
2022,6,64
2022,7,69
2022,8,57
2022,9,64
2022,10,63
2022,11,70
2022,12,66
2023,1,65
2023,2,51
2023,3,68
2023,4,69
2023,5,58
2023,6,62
2023,7,86
2023,8,74
2023,9,64
2023,10,67
2023,11,57
2023,12,80
2024,1,70
2024,2,63
2024,3,76
2024,4,81
2024,5,59
2024,6,58

In [ ]:
df_info.groupby('signupyear', 'signup_month').agg(
    countDistinct('customer_id').alias('total_customers'),
    countDistinct(when(col('order_id').isNotNull(), col('customer_id'))).alias('customers_who_ordered')
).withColumn(
    'conversion_rate',
    round(col('customers_who_ordered') / col('total_customers') * 100, 2)
).orderBy('signupyear', 'signup_month').display()

signupyear,signup_month,total_customers,customers_who_ordered,conversion_rate
2022,1,65,65,100.00
2022,2,61,61,100.00
2022,3,85,85,100.00
2022,4,54,54,100.00
2022,5,74,73,98.65
2022,6,64,63,98.44
2022,7,69,68,98.55
2022,8,57,56,98.25
2022,9,64,63,98.44
2022,10,63,62,98.41
2022,11,70,70,100.00
2022,12,66,65,98.48
2023,1,65,65,100.00
2023,2,51,51,100.00
2023,3,68,68,100.00
2023,4,69,68,98.55
2023,5,58,57,98.28
2023,6,62,61,98.39
2023,7,86,86,100.00
2023,8,74,74,100.00
2023,9,64,62,96.88
2023,10,67,67,100.00
2023,11,57,56,98.25
2023,12,80,80,100.00
2024,1,70,70,100.00
2024,2,63,63,100.00
2024,3,76,76,100.00
2024,4,81,81,100.00
2024,5,59,59,100.00
2024,6,58,57,98.28

# Ecommerce Sales Analytics -- PySpark ETL Project

> End-to-end ETL + analytics pipeline on Databricks: raw e-commerce CSVs to validated & joined DataFrames to four phases of business analysis.

---

## Dataset

Raw CSVs loaded from Unity Catalog volume workspace.default.tutorial_learning.

| File | Rows | Key Columns |
|---|---:|---|
| customers.csv | 2,015 (2,000 distinct) | customer_id, customer_name, city, state, country, signup_date |
| orders.csv | 10,000 | order_id, customer_id, order_date, payment_method, order_status |
| order_items.csv | 21,968 | order_id, product_id, quantity, unit_price |
| products.csv | 100 | product_id, product_name, category, price |

## Key Insights

* ~9x revenue growth from 2022 ($4.3M) to 2025 ($39.0M)
* Electronics dominates -- $63.6M (~67% of product revenue)
* UPI is the #1 payment method -- 3,823 orders, $40.7M revenue
* ~$12.4M potential lost sales (cancelled + returned orders)
* 99.4% customer conversion rate
* Gujarat is the top state ($11.1M revenue)

## Tech Stack

* Databricks Serverless compute
* PySpark DataFrame API
* Spark SQL with temp views
* Window functions (rank())
* Unity Catalog Volumes for raw-file storage

## How to Run

1. Attach a Serverless compute to this notebook.
2. Run all cells top-to-bottom.
3. Requires read access to /Volumes/workspace/default/tutorial_learning/raw/.